export const FETCH_CRUD = 'FETCH_CRUD';
export const FETCH_CRUD_SUCCESS = 'FETCH_CRUD_SUCCESS';
export const FETCH_CRUD_FAILS = 'FETCH_CRUD_FAILS';

export const CREATE_CRUD = 'CREATE_CRUD';
export const CREATE_CRUD_SUCCESS = 'CREATE_CRUD_SUCCESS';
export const CREATE_CRUD_FAILS = 'CREATE_CRUD_FAILS';

export const UPDATE_CRUD = 'UPDATE_CRUD';
export const UPDATE_CRUD_SUCCESS = 'UPDATE_CRUD_SUCCESS';
export const UPDATE_CRUD_FAILS = 'UPDATE_CRUD_FAILS';

export const DELETE_CRUD = 'DELETE_CRUD';
export const DELETE_CRUD_SUCCESS = 'DELETE_CRUD_SUCCESS';
export const DELETE_CRUD_FAILS = 'DELETE_CRUD_FAILS';